name: Gif 

on:
  workflow_dispatch:
    inputs:
      gif:
        description: 'gif to show'
        required: true
        default: 'borat'

jobs:
  gif:
    runs-on: ubuntu-latest
    steps:
    - run: |
        INPUT="${{ github.event.inputs.gif }}"
        QUERY="${INPUT// /+}"
        RESPONSE=$(curl "http://api.giphy.com/v1/gifs/search?q=${QUERY}&api_key=${{ secrets.GIPHY_API_KEY }}&limit=1&rating=pg")
        URL=$(echo $RESPONSE | jq -r '.data[0].embed_url')
        echo $URL
        
