name: Gif 

on:
  workflow_dispatch:
    inputs:
      gif:
        description: 'gif to show'
        required: true
        default: 'borat'

jobs:
  gif:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
      
    - name: Update Readme
      run: |
        INPUT="${{ github.event.inputs.gif }}"
        QUERY="${INPUT// /+}"
        RESP=$(curl "http://api.giphy.com/v1/gifs/search?q=${QUERY}&api_key=${{ secrets.GIPHY_API_KEY }}&limit=1&rating=pg")
        IMAGE_URL=$(echo $RESP | jq -r '.data[0].images.original.url')
        
        echo "# workflow-dispatch-example" > README.md
        echo "![${INPUT}](${IMAGE_URL})" >> README.md

    - name: Git Push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add README.md
        git commit -m "update README.md"
        git push
         
