name: Gif 

on:
  workflow_dispatch:
    inputs:
      gif:
        description: 'gif to show'
        required: true
        default: 'borat'

jobs:
  gif:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
      
    - run: |
        INPUT="${{ github.event.inputs.gif }}"
        QUERY="${INPUT// /+}"
        curl "http://api.giphy.com/v1/gifs/search?q=${QUERY}&api_key=${{ secrets.GIPHY_API_KEY }}&limit=1&rating=pg" > data.json      
    
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add data.json
        git commit -m "update data.json"
        git push
        
        
